# New Section

In [ ]:
import pandas as pd
df = pd.read_csv("/content/fire_archive2010-2016.csv")
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,31.7211,77.1063,304.2,1.4,1.2,01-01-2002,526,Terra,MODIS,53,6.03,286.2,10.6,D,0
1,31.7253,77.1147,304.3,1.4,1.2,01-01-2002,526,Terra,MODIS,52,6.03,287.3,10.7,D,0
2,30.0876,79.8322,303.1,1.0,1.0,01-01-2002,526,Terra,MODIS,12,6.03,292.7,7.1,D,0
3,30.3180,79.5568,307.1,1.1,1.0,01-01-2002,526,Terra,MODIS,51,6.03,285.5,9.0,D,0
4,25.2167,82.3508,304.7,1.1,1.1,01-01-2002,527,Terra,MODIS,0,6.03,294.7,6.1,D,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,30.5573,75.8242,315.2,1.5,1.2,08-11-2016,606,Terra,MODIS,67,6.03,302.1,11.8,D,0
1048571,30.5602,75.8085,314.7,1.5,1.2,08-11-2016,606,Terra,MODIS,66,6.03,302.8,10.6,D,0
1048572,30.6449,75.4149,313.3,1.5,1.2,08-11-2016,606,Terra,MODIS,61,6.03,302.1,8.5,D,0
1048573,30.6770,75.2999,311.7,1.4,1.2,08-11-2016,606,Terra,MODIS,55,6.03,301.2,6.5,D,0
1048574,30.7494,74.9604,321.7,1.4,1.2,08-11-2016,606,Terra,MODIS,75,6.03,301.7,20.4,D,0

In [ ]:
df.columns

Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type'],
      dtype='object')

In [ ]:
df.shape

(1048575, 15)

In [ ]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=1048575, step=1)
Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type'],
      dtype='object')

In [ ]:
import pandas as pd

# hour column create
df["hour"] = df["acq_time"] // 100

In [ ]:
hour_counts = df["hour"].value_counts().sort_index()
print(hour_counts)

hour
3       1693
4      41211
5     165612
6     116508
7     315165
8     317951
9       1789
14         5
15      4898
16     30998
17     29664
18       101
19      5739
20     15780
21      1461
Name: count, dtype: int64

In [ ]:
max_hour = hour_counts.idxmax()
print("🔥 Ekkuva fires unna hour:", max_hour)

🔥 Ekkuva fires unna hour: 8

In [ ]:
table = hour_counts.reset_index()
table.columns = ["Hour", "Fire_Count"]
print(table)

    Hour  Fire_Count
0      3        1693
1      4       41211
2      5      165612
3      6      116508
4      7      315165
5      8      317951
6      9        1789
7     14           5
8     15        4898
9     16       30998
10    17       29664
11    18         101
12    19        5739
13    20       15780
14    21        1461

In [ ]:
high_fire_hours = hour_counts[hour_counts > 1500]
print(high_fire_hours)

hour
3       1693
4      41211
5     165612
6     116508
7     315165
8     317951
9       1789
15      4898
16     30998
17     29664
19      5739
20     15780
Name: count, dtype: int64

In [ ]:
import pandas as pd

df = pd.read_csv('/content/fire_archive2010-2016.csv')

# date ni datetime ga convert
df["acq_date"] = pd.to_datetime(df["acq_date"], dayfirst=True)

# year extract
df["year"] = df["acq_date"].dt.year

print(df["year"].head())

0    2002
1    2002
2    2002
3    2002
4    2002
Name: year, dtype: int32

In [ ]:
import pandas as pd

df = pd.read_csv("/content/fire_archive2010-2016.csv")

# date format correct conversion
df['acq_date'] = pd.to_datetime(df['acq_date'], dayfirst=True, errors='coerce')

# months check
print(df['acq_date'].dt.month.unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [ ]:
print(df['acq_date'].dt.month_name().unique())

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August'
 'September' 'October' 'November' 'December']

In [ ]:
import pandas as pd

df = pd.read_csv('/content/fire_archive2010-2016.csv')

# date convert
df["acq_date"] = pd.to_datetime(df["acq_date"], dayfirst=True)

# year extract
df["year"] = df["acq_date"].dt.year

# unique years print
years = sorted(df["year"].unique())
print("CSV lo unna years:")
print(years)

CSV lo unna years:
[np.int32(2002), np.int32(2003), np.int32(2004), np.int32(2005), np.int32(2006), np.int32(2007), np.int32(2008), np.int32(2009), np.int32(2010), np.int32(2011), np.int32(2012), np.int32(2013), np.int32(2014), np.int32(2015), np.int32(2016)]

In [ ]:
import pandas as pd

df = pd.read_csv("/content/fire_archive2010-2016.csv")

df['acq_date'] = pd.to_datetime(df['acq_date'], dayfirst=True)

df = df[(df['acq_date'].dt.year>=2010) & (df['acq_date'].dt.year<=2016)]
df.to_csv("fire_2010_2016.csv",index=False)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/fire_archive2010-2016.csv')

# date convert
df["acq_date"] = pd.to_datetime(df["acq_date"], dayfirst=True)

# month extract
df["month"] = df["acq_date"].dt.month

# month wise fire count
month_counts = df["month"].value_counts().sort_index()

print("Month wise fire counts:\n")
print(month_counts)

Month wise fire counts:

month
1      48268
2      90217
3     309624
4     182137
5      95875
6      12602
7       3126
8       3215
9       6686
10    151880
11    107373
12     37572
Name: count, dtype: int64

In [ ]:
import pandas as pd

df = pd.read_csv("/fire_archive2010-2016.csv")

df['acq_date'] = pd.to_datetime(df['acq_date'], dayfirst=True)

print("Data available from year:", df['acq_date'].dt.year.min())
print("Data available till year:", df['acq_date'].dt.year.max())

Data available from year: 2002
Data available till year: 2016

In [ ]:
print("Start date of CSV:", df['acq_date'].min())
print("End date of CSV:", df['acq_date'].max())

Start date of CSV: 2002-01-01 00:00:00
End date of CSV: 2016-11-08 00:00:00

In [ ]:
import pandas as pd

fire = pd.read_csv('/content/fire_archive2010-2016.csv')
fire['acq_date'] = pd.to_datetime(fire['acq_date'], dayfirst=True)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/fire_archive2010-2016.csv')

# date convert
df["acq_date"] = pd.to_datetime(df["acq_date"], dayfirst=True)

# year extract
df["year"] = df["acq_date"].dt.year

# year wise fire count
year_counts = df["year"].value_counts()

# ekkuva nunchi thakkuva varaku sort
sorted_years = year_counts.sort_values(ascending=False)

print("🔥 Ekkuva fires nunchi thakkuva fires varaku years:\n")
print(sorted_years)

🔥 Ekkuva fires nunchi thakkuva fires varaku years:

year
2012    93259
2009    90325
2014    76738
2010    76723
2016    75418
2007    75385
2011    72464
2013    71341
2008    70978
2015    68626
2006    66034
2004    64776
2005    63543
2003    56142
2002    26823
Name: count, dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_csv("/content/fire_archive2010-2016.csv")
df['acq_date'] = pd.to_datetime(df['acq_date'], dayfirst=True)

print("Start year:", df['acq_date'].dt.year.min())
print("End year:", df['acq_date'].dt.year.max())

Start year: 2002
End year: 2016

In [ ]:
import os

os.listdir('/content/drive/MyDrive')

['Resume.pdf',
 'Tambirani Resume  (3).pdf',
 'Tambirani Resume  (2).gdoc',
 'Tambirani Resume  (2).pdf',
 'Classroom',
 'Hostel ANU',
 'Drive',
 'IMG_20250204_204021.jpg',
 'Python assignment ',
 'unit 1python ',
 'Colab Notebooks',
 'rainfall_ond2022.xlsx',
 'IND_adm.zip',
 'data_stream-oper_stepType-instant.nc',
 'fire_archive_M-C61_597338 - Copy.csv',
 'Internship Project Report On (1).docx',
 'final internship report_Rani.pdf',
 'Internship Project Report On.docx',
 'final internship report_Rani.gdoc',
 'coalpublic2013.gsheet',
 'Resume (2).gdoc',
 'indian population new.csv',
 'Resume (1).gdoc',
 'Resume.gdoc',
 'Tambirani Resume  (1).gdoc',
 'Tambirani Resume  (1).pdf',
 'Tambirani Resume .gdoc',
 'Tambirani Resume .pdf',
 'resume.gdoc',
 'resume.pdf',
 'research paper.pdf',
 'population prediction using machine learning .pdf',
 'population prediction using machine learning .docx',
 'Read me file .gdoc',
 'Read me file .pdf',
 'Netcdf files',
 'ERA5',
 'project']

In [ ]:
os.listdir('/content/drive/MyDrive/project')

['data_stream-oper_stepType-accum (2).nc',
 'data_stream-oper_stepType-instant (2).nc',
 'data_stream-oper_stepType-instant.nc',
 'data_stream-oper_stepType-accum.nc']

In [ ]:
import xarray as xr

files_instant = [
"/content/drive/MyDrive/project/data_stream-oper_stepType-instant.nc",
"/content/drive/MyDrive/project/data_stream-oper_stepType-instant (2).nc"
]

ds_instant = xr.open_mfdataset(files_instant, combine='by_coords')

ds_instant

<xarray.Dataset> Size: 1GB
Dimensions:     (valid_time: 5479, latitude: 125, longitude: 117)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 44kB 2002-01-01T05:00:00 ... 2016...
  * latitude    (latitude) float64 1kB 37.0 36.75 36.5 36.25 ... 6.5 6.25 6.0
  * longitude   (longitude) float64 936B 68.0 68.25 68.5 ... 96.5 96.75 97.0
    number      int64 8B 0
    expver      (valid_time) <U4 88kB dask.array<chunksize=(2557,), meta=np.ndarray>
Data variables:
    u10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    v10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    d2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    t2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-02-24T04:48 GRIB to CDM+CF via cfgrib-0.9.1...

In [ ]:
files_accum = [
"/content/drive/MyDrive/project/data_stream-oper_stepType-accum.nc",
"/content/drive/MyDrive/project/data_stream-oper_stepType-accum (2).nc"
]

ds_accum = xr.open_mfdataset(files_accum, combine='by_coords')

ds_accum

<xarray.Dataset> Size: 321MB
Dimensions:     (valid_time: 5479, latitude: 125, longitude: 117)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 44kB 2002-01-01T05:00:00 ... 2016...
  * latitude    (latitude) float64 1kB 37.0 36.75 36.5 36.25 ... 6.5 6.25 6.0
  * longitude   (longitude) float64 936B 68.0 68.25 68.5 ... 96.5 96.75 97.0
    number      int64 8B 0
    expver      (valid_time) <U4 88kB dask.array<chunksize=(2557,), meta=np.ndarray>
Data variables:
    tp          (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-02-24T04:48 GRIB to CDM+CF via cfgrib-0.9.1...

In [ ]:
ds = xr.merge([ds_instant, ds_accum])
ds

/tmp/ipython-input-1282922367.py:1: FutureWarning: In a future version of xarray the default value for compat will change from compat='no_conflicts' to compat='override'. This is likely to lead to different results when combining overlapping variables with the same name. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set compat explicitly.
  ds = xr.merge([ds_instant, ds_accum])
/tmp/ipython-input-1282922367.py:1: FutureWarning: In a future version of xarray the default value for compat will change from compat='no_conflicts' to compat='override'. This is likely to lead to different results when combining overlapping variables with the same name. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set compat explicitly.
  ds = xr.merge([ds_instant, ds_accum])

<xarray.Dataset> Size: 2GB
Dimensions:     (valid_time: 5479, latitude: 125, longitude: 117)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 44kB 2002-01-01T05:00:00 ... 2016...
  * latitude    (latitude) float64 1kB 37.0 36.75 36.5 36.25 ... 6.5 6.25 6.0
  * longitude   (longitude) float64 936B 68.0 68.25 68.5 ... 96.5 96.75 97.0
    number      int64 8B 0
    expver      (valid_time) <U4 88kB dask.array<chunksize=(2557,), meta=np.ndarray>
Data variables:
    u10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    v10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    d2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    t2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    tp          (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-02-24T04:48 GRIB to CDM+CF via cfgrib-0.9.1...

In [ ]:
print("Start date:", ds.valid_time.values[0])
print("End date:", ds.valid_time.values[-1])

Start date: 2002-01-01T05:00:00.000000000
End date: 2016-12-31T05:00:00.000000000

In [ ]:
print("Start year:", str(ds.valid_time.values[0])[:4])
print("End year:", str(ds.valid_time.values[-1])[:4])

Start year: 2002
End year: 2016

In [ ]:
ds_5am = ds.sel(valid_time = ds['valid_time'].dt.hour == 5)

ds_5am

<xarray.Dataset> Size: 2GB
Dimensions:     (valid_time: 5479, latitude: 125, longitude: 117)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 44kB 2002-01-01T05:00:00 ... 2016...
  * latitude    (latitude) float64 1kB 37.0 36.75 36.5 36.25 ... 6.5 6.25 6.0
  * longitude   (longitude) float64 936B 68.0 68.25 68.5 ... 96.5 96.75 97.0
    number      int64 8B 0
    expver      (valid_time) <U4 88kB dask.array<chunksize=(2557,), meta=np.ndarray>
Data variables:
    u10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    v10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    d2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    t2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    tp          (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-02-24T04:48 GRIB to CDM+CF via cfgrib-0.9.1...

In [ ]:
ds_5am.t2m.shape

(5479, 125, 117)

In [ ]:
import numpy as np

print(np.unique(ds['valid_time'].dt.hour))

[5]

In [ ]:
import numpy as np

fire_array = np.zeros(ds.t2m.shape)

fire_array.shape

(5479, 125, 117)

In [ ]:
times = ds_5am.valid_time.values
lats = ds_5am.latitude.values
lons = ds_5am.longitude.values

In [ ]:
fire['acq_date'] = pd.to_datetime(fire['acq_date'])

In [ ]:
import numpy as np

# Wind speed
ds['wind_speed'] = np.sqrt(ds['u10']**2 + ds['v10']**2)

# Temperature in Celsius
ds['tem_c'] = ds['t2m'] - 273.15

ds.data_vars

Data variables:
    u10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    v10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    d2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    t2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    tp          (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    wind_speed  (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    tem_c       (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>

In [ ]:
fire['acq_date']

0         2002-01-01
1         2002-01-01
2         2002-01-01
3         2002-01-01
4         2002-01-01
             ...
1048570   2016-11-08
1048571   2016-11-08
1048572   2016-11-08
1048573   2016-11-08
1048574   2016-11-08
Name: acq_date, Length: 1048575, dtype: datetime64[ns]

In [ ]:
fire['acq_time'] = fire['acq_time'].astype(str).str.zfill(4)
fire['hour'] = fire['acq_time'].str[:2].astype(int)

In [ ]:
fire[['acq_date','hour']].head()

    acq_date  hour
0 2002-01-01     5
1 2002-01-01     5
2 2002-01-01     5
3 2002-01-01     5
4 2002-01-01     5

In [ ]:
fire = fire[fire['hour'] == 5]
print(len(fire))

165612

In [ ]:
fire_array.sum()

np.float64(98607.0)

In [ ]:
ds['fire'] = (('valid_time','latitude','longitude'), fire_array)

ds

<xarray.Dataset> Size: 3GB
Dimensions:     (valid_time: 5479, latitude: 125, longitude: 117)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 44kB 2002-01-01T05:00:00 ... 2016...
  * latitude    (latitude) float64 1kB 37.0 36.75 36.5 36.25 ... 6.5 6.25 6.0
  * longitude   (longitude) float64 936B 68.0 68.25 68.5 ... 96.5 96.75 97.0
    number      int64 8B 0
    expver      (valid_time) <U4 88kB dask.array<chunksize=(2557,), meta=np.ndarray>
Data variables:
    u10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    v10         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    d2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    t2m         (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    tp          (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    wind_speed  (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    tem_c       (valid_time, latitude, longitude) float32 321MB dask.array<chunksize=(853, 42, 39), meta=np.ndarray>
    fire        (valid_time, latitude, longitude) float64 641MB 0.0 0.0 ... 0.0
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-02-24T04:48 GRIB to CDM+CF via cfgrib-0.9.1...

In [ ]:
ds.to_netcdf('/content/final_fire_weather_dataset.nc')

In [ ]:
import xarray as xr

ds = xr.open_dataset('/content/final_fire_weather_dataset.nc')
ds

<xarray.Dataset> Size: 3GB
Dimensions:     (valid_time: 5479, latitude: 125, longitude: 117)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 44kB 2002-01-01T05:00:00 ... 2016...
  * latitude    (latitude) float64 1kB 37.0 36.75 36.5 36.25 ... 6.5 6.25 6.0
  * longitude   (longitude) float64 936B 68.0 68.25 68.5 ... 96.5 96.75 97.0
    number      int64 8B ...
    expver      (valid_time) <U4 88kB ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 321MB ...
    v10         (valid_time, latitude, longitude) float32 321MB ...
    d2m         (valid_time, latitude, longitude) float32 321MB ...
    t2m         (valid_time, latitude, longitude) float32 321MB ...
    tp          (valid_time, latitude, longitude) float32 321MB ...
    wind_speed  (valid_time, latitude, longitude) float32 321MB ...
    tem_c       (valid_time, latitude, longitude) float32 321MB ...
    fire        (valid_time, latitude, longitude) float64 641MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-02-24T04:48 GRIB to CDM+CF via cfgrib-0.9.1...

In [ ]:
import numpy as np

X = np.stack([
    ds['tem_c'].values,
    ds['tp'].values,
    ds['wind_speed'].values,
    ds['d2m'].values
], axis=-1)

y = ds['fire'].values

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (5479, 125, 117, 4)
y shape: (5479, 125, 117)

In [ ]:
X_flat = X.reshape(-1, 4)
y_flat = y.reshape(-1)

print(X_flat.shape)
print(y_flat.shape)

(80130375, 4)
(80130375,)

In [ ]:
import numpy as np

# fire indices
fire_idx = np.where(y_flat == 1)[0]

# no fire indices
nofire_idx = np.where(y_flat == 0)[0]

# equal no fire select
nofire_sample = np.random.choice(nofire_idx, size=len(fire_idx), replace=False)

# combine
final_idx = np.concatenate([fire_idx, nofire_sample])

X_bal = X_flat[final_idx]
y_bal = y_flat[final_idx]

print(X_bal.shape, y_bal.shape)

(197214, 4) (197214,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_bal, y_bal, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

(157771, 4) (39443, 4)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# create model
model = LogisticRegression(max_iter=1000)

# train
model.fit(X_train, y_train)

# predict
y_pred = model.predict(X_test)

# accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7938290697969221
              precision    recall  f1-score   support

         0.0       0.80      0.79      0.79     19815
         1.0       0.79      0.80      0.79     19628

    accuracy                           0.79     39443
   macro avg       0.79      0.79      0.79     39443
weighted avg       0.79      0.79      0.79     39443

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf = RandomForestClassifier(
    n_estimators=300,     # trees increase
    max_depth=18,         # deeper learning
    min_samples_split=5,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8353827041553634
              precision    recall  f1-score   support

         0.0       0.90      0.76      0.82     19815
         1.0       0.79      0.91      0.85     19628

    accuracy                           0.84     39443
   macro avg       0.84      0.84      0.83     39443
weighted avg       0.84      0.84      0.83     39443

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8368024744568111
              precision    recall  f1-score   support

         0.0       0.90      0.76      0.82     19815
         1.0       0.79      0.91      0.85     19628

    accuracy                           0.84     39443
   macro avg       0.85      0.84      0.84     39443
weighted avg       0.85      0.84      0.84     39443

In [ ]:
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# scaling
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

# tuned xgboost
xgb = XGBClassifier(
    n_estimators=500,
    max_depth=10,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42,
    n_jobs=-1,
    eval_metric='logloss'
)

xgb.fit(X_train_s, y_train)

y_pred = xgb.predict(X_test_s)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.835610881525239
              precision    recall  f1-score   support

         0.0       0.90      0.76      0.82     19815
         1.0       0.79      0.91      0.85     19628

    accuracy                           0.84     39443
   macro avg       0.84      0.84      0.83     39443
weighted avg       0.84      0.84      0.83     39443

In [ ]:
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_bal)

X_tensor = torch.tensor(X_scaled, dtype=torch.float32)
y_tensor = torch.tensor(y_bal, dtype=torch.long)

print(X_tensor.shape)

torch.Size([197214, 4])

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# dataset
dataset = TensorDataset(X_tensor, y_tensor)
loader = DataLoader(dataset, batch_size=512, shuffle=True)

# transformer model
class FireTransformer(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(4, 64)
        self.transformer = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(d_model=64, nhead=4),
            num_layers=2
        )
        self.fc2 = nn.Linear(64, 2)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = x.unsqueeze(1)          # add sequence dim
        x = self.transformer(x)
        x = x.squeeze(1)
        return self.fc2(x)

model = FireTransformer()

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# training
for epoch in range(5):
    total_loss = 0
    for xb, yb in loader:
        pred = model(xb)
        loss = criterion(pred, yb)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss:", total_loss)

/tmp/ipython-input-1613789060.py:14: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  self.transformer = nn.TransformerEncoder(

Epoch 1, Loss: 150.19365751743317
Epoch 2, Loss: 145.69967317581177
Epoch 3, Loss: 145.02146500349045
Epoch 4, Loss: 144.81535214185715
Epoch 5, Loss: 144.56638011336327

In [ ]:
# evaluation
model.eval()

with torch.no_grad():
    outputs = model(X_tensor)
    _, predicted = torch.max(outputs, 1)
    correct = (predicted == y_tensor).sum().item()
    accuracy = correct / len(y_tensor)

print("Transformer Accuracy:", accuracy)

Transformer Accuracy: 0.832811058038476

In [122]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# reshape for CNN (samples, channels, features)
X_cnn = torch.tensor(X_bal, dtype=torch.float32).unsqueeze(1)
y_cnn = torch.tensor(y_bal, dtype=torch.long)

dataset = TensorDataset(X_cnn, y_cnn)
loader = DataLoader(dataset, batch_size=512, shuffle=True)

# CNN model
class FireCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv1d(1, 16, kernel_size=2)
        self.conv2 = nn.Conv1d(16, 32, kernel_size=2)
        self.fc1 = nn.Linear(32*2, 64)
        self.fc2 = nn.Linear(64, 2)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.conv1(x))
        x = self.relu(self.conv2(x))
        x = x.view(x.size(0), -1)
        x = self.relu(self.fc1(x))
        return self.fc2(x)

model = FireCNN()

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# training
for epoch in range(5):
    total_loss = 0
    for xb, yb in loader:
        pred = model(xb)
        loss = criterion(pred, yb)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss:", total_loss)

Epoch 1, Loss: 204.73880064487457
Epoch 2, Loss: 194.217547416687
Epoch 3, Loss: 191.12240329384804
Epoch 4, Loss: 188.3571399450302
Epoch 5, Loss: 184.22630110383034

In [123]:
# evaluation
model.eval()

with torch.no_grad():
    outputs = model(X_cnn)
    _, predicted = torch.max(outputs, 1)
    correct = (predicted == y_cnn).sum().item()
    acc = correct / len(y_cnn)

print("CNN Accuracy:", acc)

CNN Accuracy: 0.732524060158001

In [124]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report

lgb = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=12,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

lgb.fit(X_train, y_train)

y_pred = lgb.predict(X_test)

print("LightGBM Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[LightGBM] [Info] Number of positive: 78979, number of negative: 78792
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.033533 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1020
[LightGBM] [Info] Number of data points in the train set: 157771, number of used features: 4
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500593 -> initscore=0.002371
[LightGBM] [Info] Start training from score 0.002371

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

LightGBM Accuracy: 0.8374616535253404
              precision    recall  f1-score   support

         0.0       0.90      0.76      0.82     19815
         1.0       0.79      0.92      0.85     19628

    accuracy                           0.84     39443
   macro avg       0.85      0.84      0.84     39443
weighted avg       0.85      0.84      0.84     39443

In [125]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# tensor data
X_dnn = torch.tensor(X_bal, dtype=torch.float32)
y_dnn = torch.tensor(y_bal, dtype=torch.long)

dataset = TensorDataset(X_dnn, y_dnn)
loader = DataLoader(dataset, batch_size=512, shuffle=True)

# deep neural network
class DNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(4, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 2)
        )

    def forward(self, x):
        return self.net(x)

model = DNN()

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# training
for epoch in range(10):
    total_loss = 0
    for xb, yb in loader:
        pred = model(xb)
        loss = criterion(pred, yb)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss:", total_loss)

Epoch 1, Loss: 218.86750772595406
Epoch 2, Loss: 199.2024297118187
Epoch 3, Loss: 195.14705830812454
Epoch 4, Loss: 193.00497925281525
Epoch 5, Loss: 191.0334845483303
Epoch 6, Loss: 189.3275189101696
Epoch 7, Loss: 187.4394227564335
Epoch 8, Loss: 186.72520235180855
Epoch 9, Loss: 186.40464380383492
Epoch 10, Loss: 185.92810782790184

In [126]:
# evaluation
model.eval()

with torch.no_grad():
    outputs = model(X_dnn)
    _, predicted = torch.max(outputs, 1)
    correct = (predicted == y_dnn).sum().item()
    acc = correct / len(y_dnn)

print("DNN Accuracy:", acc)

DNN Accuracy: 0.7543987749348423

In [ ]:
from google.colab import drive
drive.mount('/content/drive')